config/routes.rb
DbPassi::Application.routes.draw do
  resources :users

  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :passes do 
    resources :localities, shallow: true
  end

  match 'map' => 'passes#map', :as => :map

  post 'passes/search' => 'passes#search', :as => :passes_search

  root :to => 'passes#index'

end

app/models/locality.rb
class Locality < ActiveRecord::Base
  attr_accessible :pass_id #, :fraction_id, :municipality_id
  belongs_to :pass
  belongs_to :localitiable, polymorphic: true
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
	# GET /passes
  # GET /passes.json
  def index
    @localities = Locality.where(:pass_id => params[:pass_id])
    @list = []
    @localities.each do |locality|
      @list << getLocality(locality)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list }
    end
  end

  # GET /passes/1
  # GET /passes/1.json
  def show
    @locality = Locality.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /passes/new
  # GET /passes/new.json
  def new
    @locality = Locality.new

    @pass = nil
    if params[:pass_id]
      @pass = Pass.find(params[:pass_id].to_i)
    else
      @pass = Pass.all.first
    end
    @object = [@pass, @locality]


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @locality }
    end
  end

  # GET /passes/1/edit
  def edit
    @locality = Locality.find(params[:id])
    @pass = @locality.pass
    @object = @locality
  end

  # POST /passes
  # POST /passes.json
  def create
    @locality = Locality.new(params[:locality])

    respond_to do |format|
      if @locality.save
        format.html { redirect_to @locality, notice: 'Locality was successfully created.' }
        format.json { render json: @locality, status: :created, location: @locality }
      else
        format.html { render action: "new" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /passes/1
  # PUT /passes/1.json
  def update
    @locality = Locality.find(params[:id])

    respond_to do |format|
      if @locality.update_attributes(params[:locality])
        format.html { redirect_to @locality, notice: 'Locality was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passes/1
  # DELETE /passes/1.json
  def destroy
    @locality = Locality.find(params[:id])
    @pass = @locality.pass
    @locality.destroy


    respond_to do |format|
      format.html { redirect_to @pass }
      format.json { head :no_content }
    end
  end

  private

  def getLocality locality
    if locality.fraction_id.nil?
      return Municipality.find(locality.municipality_id)
    else
      return Fraction.find(locality.fraction_id)
    end
  end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.erb
<%= simple_form_for(@object, html: { class: 'form-horizontal' }) do |f| %>
  
  <%= f.input :name, :label => "Name", :placeholder => "Name" %>

  <%= render "forms/create_edit_buttons", :f => f %>
<% end %>

app/views/localities/_index.html.erb
<legend>Localities (<%= @localities.size.to_s %>)</legend>
<%#= link_to 'New Locality', new_pass_locality_path(@pass), 
  :class => "btn btn-success" if current_user %>
<br/><br/>
<% if !@localities.empty? %>

  <%#= alphabetical_paginate @alphaParams %>
  <!-- <div id="pagination_table"> -->
  <table class="table table-hover table-striped">
    <tr>
      <th>#</th>
      <th>Municipality</th>
      <th>Fraction</th>
      <% if current_user %>
        <!-- <th></th> -->
        <th></th>
      <% end %>
    </tr>

    <% @localities.each_with_index do |locality,index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= locality.municipality.name if !locality.municipality.nil? %></td>
      <td><%= locality.fraction.name if !locality.fraction.nil? %></td>
      <% if current_user %>
        <!-- <td><%#= link_to 'Edit', edit_locality_path(locality), 
          :class => "btn btn-primary" %></td> -->
        <td><%= link_to 'Destroy', locality, method: :delete, 
          data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      <% end %>
    </tr>
    <% end %>
  </table>
  <!-- </div> -->

<% else %>
<p class="muted">
  <i>No localities for this pass!</i>
</p>
<% end %>

app/views/localities/edit.html.erb
<br/>
<center><h2>Edit Locality</h2></center>
<br/>
<%= render 'form' %>

app/views/localities/new.html.erb
<br/>
<center><h2>Create Locality</h2></center>
<br/>
<%= render 'form' %>