config/routes.rb
DbPassi::Application.routes.draw do
  resources :users

  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :passes do 
    resources :localities, shallow: true
  end

  match 'map' => 'passes#map', :as => :map

  post 'passes/search' => 'passes#search', :as => :passes_search

  root :to => 'passes#index'

end

app/controllers/passes_controller.rb
class PassesController < ApplicationController
  require "#{Rails.root}/lib/tasks/task_utilities"
  include TaskUtilities

  def search
    name = encode(params[:name]) if params[:name]
    @passes = findItemByName("Pass", name)

    respond_to do |format|
      format.json { render json: @passes }
    end

  end

  # GET /passes
  # GET /passes.json
  def index
    @passes, @alphaParams = 
       Pass.all.alpha_paginate(params[:letter], {:js => true}){|pass| pass.name}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @passes }
    end
  end

  def map
    @passes = Pass.where("latitude IS NOT NULL")

    @markers = Gmaps4rails.build_markers(@passes) do |pass, marker|
      marker.lat pass.latitude
      marker.lng pass.longitude
      marker.title pass.id.to_s
      marker.infowindow pass.name
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /passes/1
  # GET /passes/1.json
  def show
    @pass = Pass.find(params[:id])
    @localities = @pass.localities

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pass }
    end
  end

  # GET /passes/new
  # GET /passes/new.json
  def new
    @pass = Pass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pass }
    end
  end

  # GET /passes/1/edit
  def edit
    @pass = Pass.find(params[:id])
  end

  # POST /passes
  # POST /passes.json
  def create
    @pass = Pass.new(params[:pass])

    respond_to do |format|
      if @pass.save
        format.html { redirect_to @pass, notice: 'Pass was successfully created.' }
        format.json { render json: @pass, status: :created, location: @pass }
      else
        format.html { render action: "new" }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /passes/1
  # PUT /passes/1.json
  def update
    @pass = Pass.find(params[:id])

    respond_to do |format|
      if @pass.update_attributes(params[:pass])
        format.html { redirect_to @pass, notice: 'Pass was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passes/1
  # DELETE /passes/1.json
  def destroy
    @pass = Pass.find(params[:id])
    @pass.destroy

    respond_to do |format|
      format.html { redirect_to passes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/views/passes/_form.html.erb
<%= simple_form_for(@pass) do |f| %>
  <% f.input :name, :label => "Name", :placeholder => "Name" %>
  <% f.input :altitude, :label => "Altitude", :placeholder => "Altitude" %>
  <%= f.submit %>
<% end %>

app/views/passes/edit.html.erb
<h1>Editing pass</h1>

<%= render 'form' %>

<%= link_to 'Show', @pass %> |
<%= link_to 'Back', passes_path %>

app/views/passes/index.html.erb
<br/>
<center><h2>List of Passes</h2></center>
<hr/>
<%= link_to 'New Pass', new_pass_path, :class => "btn btn-success" if current_user %>
<%= alphabetical_paginate @alphaParams %>
<div id="pagination_table">
<table class="table table-hover table-striped">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Altitude</th>
    <% if current_user %>
        <th></th>
        <th></th>
    <% end %>
  </tr>

<% @passes.each_with_index do |pass,index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= link_to pass.name, pass %></td>
    <td><%= pass.altitude %></td>
    <% if current_user %>
        <td><%= link_to 'Edit', edit_pass_path(pass), 
            :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', pass, method: :delete, 
            data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>
<br />

app/views/passes/map.html.erb
<div id="map"></div>

<script type="text/javascript">

handler = Gmaps.build('Google', { 
	builders: { Marker: InfoBoxBuilder},
	markers:
    {clusterer: {
      gridSize: 40,
      maxZoom: 10,
      styles: [
      	{
				height: 53,
				width: 53,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m1.png"
				},
				{
				height: 56,
				width: 56,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m2.png"
				},
				{
				height: 66,
				width: 66,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m3.png"
				},
				{
				height: 78,
				width: 78,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m4.png"
				},
				{
				height: 90,
				width: 90,
				url: "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m5.png"
				}
			]
  	}
  }
});

handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @markers.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();

   //  for (var i=0;i < markers.length; i++){
	  //   var marker = markers[i];
	  //   google.maps.event.addListener(
	  //   	markers[i].getServiceObject(), 
	  //   	"click", 
	  //   	function(event) {
	  //   		$.get("/municipalities/" + this.title + "/infobox", function( data ) {
			// 		  $("div.infobox1").html( data );
			// 		});
	  //   	}
	  //   );
	  // }

});

</script>

<style>

  #map {
    height: 100%;
    width: 100%;
    margin: 0px;
    padding: 0px;
    min-height: 100%;
  }

  #map img { 
  	max-width: none;
	}

	#map label { 
	  width: auto; display:inline; 
	} 

	.infobox1 {
      border:1px solid #d5d5d5;
      margin-top: 8px;
      background:#fefefe;
      font-family:Arial, Helvetica, sans-serif;
      font-size:12px;
      padding: 1em;
      -webkit-border-radius: 3px;
      -moz-border-radius: 3px;
      border-radius: 3px;
      -webkit-box-shadow: 0 0  5px #acacac;
      box-shadow: 0 0 5px #acacac;
  }

  .infoBox img{
  	margin-top: 10px !important; 
		margin-right: 2px !important;
  }
</style>

app/views/passes/new.html.erb
<h1>New pass</h1>

<%= render 'form' %>

<%= link_to 'Back', passes_path %>

app/views/passes/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
<center><h2><%= @pass.name %></h2></center>
<hr/>

<p>
  <b>Altitude:</b>
  <%= @pass.altitude %> metri
</p>

<p>
  <b>Latitude:</b>
  <%= @pass.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @pass.longitude %>
</p>

<% if current_user %>

  <br/>

  <%= link_to command_label('fa fa-edit', "Edit"), 
      edit_pass_path(@pass), :class=> "btn btn-primary" %>

  <%= link_to command_label('fa fa-trash-o', "Destroy"), 
      @pass, method: :delete, data: { confirm: 'Are you sure?' }, 
      :class => "btn btn-danger" %>
<% end %>
<br/><br/>
<%= render "localities/index" %>