config/routes.rb
DbPassi::Application.routes.draw do
  resources :users

  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :passes do 
    resources :localities, shallow: true
  end

  match 'map' => 'passes#map', :as => :map

  post 'passes/search' => 'passes#search', :as => :passes_search

  root :to => 'passes#index'

end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">Passes</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li id="list-item"><%= link_to "List", passes_path %></li>
          <li id="map-item"><%= link_to "Map", map_path %></li>          
        </ul>
        <ul class="nav pull-right">
          <% if current_user %>
            <li id="logout-item"><%= link_to "Logout", :logout%></li>  
          <% else %>
            <li id="login-item"><%= link_to "Login", :login %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
  <% if action_name == "map" %>
    $("#map-item").addClass("active");
  <% else %>
    $("#list-item").addClass("active");
  <% end %>
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbPassi</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= javascript_include_tag "http://maps.google.com/maps/api/js?key=AIzaSyB9XMLYNp-bKeDbBeHrVsrypkzWcqXi7NA&libraries=geometry&sensor=true&language=it" %>
  <%= javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= javascript_include_tag "http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js" %>
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>

<div class="container-fluid">
	<% flash.each do |key, msg| %>
	  <%= content_tag(:div, msg, class: "flash alert alert-#{key}", style: "margin-top:20px;") %>
	<% end %>

	<%= yield %>
</div>

</body>
</html>